// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestAllegeQuoteResponseCodec(t *testing.T) {

	original := &msg.AllegeQuoteResponse{
		PartitionNo:      4,
		ReportIndex:      8,
		ApplId:           "xxx",
		ReportingPbuid:   "xxxxxx",
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		OrderId:          "xxxxxxxxxxxxxxxx",
		ExecId:           "xxxxxxxxxxxxxxxx",
		ClOrdId:          "xxxxxxxxxx",
		AccountId:        "xxxxxxxxxx",
		QuoteId:          "xxxxxxxxxx",
		QuoteRespId:      "xxxxxxxxxx",
		QuoteRespType:    1,
		PrivateQuote:     1,
		OrderQty:         8,
		Price:            8,
		ValidUntilTime:   8,
		QuoteType:        1,
		PriceType:        1,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.AllegeQuoteResponse
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
