// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestBjseBinaryCodec(t *testing.T) {

	body := &msg.Logon{
		SenderCompId:     "xxxxxxxxxxxxxxxxxxxx",
		TargetCompId:     "xxxxxxxxxxxxxxxxxxxx",
		HeartBtInt:       4,
		Password:         "xxxxxxxxxxxxxxxx",
		DefaultApplVerId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	original := &msg.BjseBinary{
		BodyLength: 4,
		MsgType:    1,
		Body:       body,
		Checksum:   4,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.BjseBinary
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
