// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestOrderCancelRequestCodec(t *testing.T) {

	original := &msg.OrderCancelRequest{
		ApplId:           "xxx",
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		ClOrdId:          "xxxxxxxxxx",
		OrigClOrdId:      "xxxxxxxxxx",
		AccountId:        "xxxxxxxxxx",
		BranchId:         "xx",
		OrderId:          "xxxxxxxxxxxxxxxx",
		OrderQty:         8,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.OrderCancelRequest
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
