// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestQuoteResponseCodec(t *testing.T) {

	quote2 := &msg.Quote2{
		QuoteId:    "xxxxxxxxxx",
		QuotePrice: 8,
		QuoteQty:   8,
	}
	applExtend := &msg.QuoteResponseExtend070{
		CashMargin: "x",
	}
	original := &msg.QuoteResponse{
		ReportingPbuid:   "xxxxxx",
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		ClOrdId:          "xxxxxxxxxx",
		AccountId:        "xxxxxxxxxx",
		BranchId:         "xx",
		QuoteRespId:      "xxxxxxxxxx",
		QuoteRespType:    1,
		Side:             "x",
		ValidUntilTime:   8,
		QuoteType:        1,
		PriceType:        1,
		Quote2:           []*msg.Quote2{quote2},
		ApplId:           "070",
		ApplExtend:       applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.QuoteResponse
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
