// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestQuoteExtend070Codec(t *testing.T) {

	original := &msg.QuoteExtend070{
		BranchId:          "xx",
		QuoteId:           "xxxxxxxxxx",
		QuoteRespId:       "xxxxxxxxxx",
		PrivateQuote:      1,
		ValidUntilTime:    8,
		PriceType:         1,
		CashMargin:        "x",
		CounterPartyPbuid: "xxxxxx",
		Memo:              "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.QuoteExtend070
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
