// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// QuoteResponseExtend070 represents the packet structure.
type QuoteResponseExtend070 struct {
	CashMargin string `json:"CashMargin"`
}

// NewQuoteResponseExtend070 creates a new instance of QuoteResponseExtend070.
func NewQuoteResponseExtend070() *QuoteResponseExtend070 {
	return &QuoteResponseExtend070{}
}

// String returns a string representation of the packet.
func (p *QuoteResponseExtend070) String() string {
	return fmt.Sprintf("QuoteResponseExtend070{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *QuoteResponseExtend070) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *QuoteResponseExtend070) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
