// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestQuoteCodec(t *testing.T) {

	applExtend := &msg.QuoteExtend070{
		BranchId:          "xx",
		QuoteId:           "xxxxxxxxxx",
		QuoteRespId:       "xxxxxxxxxx",
		PrivateQuote:      1,
		ValidUntilTime:    8,
		PriceType:         1,
		CashMargin:        "x",
		CounterPartyPbuid: "xxxxxx",
		Memo:              "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	original := &msg.Quote{
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		QuoteMsgId:       "xxxxxxxxxx",
		AccountId:        "xxxxxxxxxx",
		QuoteReqId:       "xxxxxxxxxx",
		QuoteType:        1,
		BidPx:            8,
		OfferPx:          8,
		BidSize:          8,
		OfferSize:        8,
		ApplId:           "070",
		ApplExtend:       applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Quote
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
