// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestQuoteStatusReportExtend070Codec(t *testing.T) {

	quote1 := &msg.Quote1{
		QuoteId:    "xxxxxxxxxx",
		QuotePrice: 8,
		QuoteQty:   8,
	}
	original := &msg.QuoteStatusReportExtend070{
		BranchId:          "xx",
		OrderId:           "xxxxxxxxxxxxxxxx",
		ExecId:            "xxxxxxxxxxxxxxxx",
		QuoteRespId:       "xxxxxxxxxx",
		PrivateQuote:      1,
		Side:              "x",
		PriceType:         1,
		ValidUntilTime:    8,
		CashMargin:        "x",
		CounterPartyPbuid: "xxxxxx",
		Memo:              "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		Quote1:            []*msg.Quote1{quote1},
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.QuoteStatusReportExtend070
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
