// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// ReportExtend040 represents the packet structure.
type ReportExtend040 struct {
	CashMargin string `json:"CashMargin"`
}

// NewReportExtend040 creates a new instance of ReportExtend040.
func NewReportExtend040() *ReportExtend040 {
	return &ReportExtend040{}
}

// String returns a string representation of the packet.
func (p *ReportExtend040) String() string {
	return fmt.Sprintf("ReportExtend040{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *ReportExtend040) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *ReportExtend040) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
