// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestTradeCaptureConfirmExtend061Codec(t *testing.T) {

	original := &msg.TradeCaptureConfirmExtend061{}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.TradeCaptureConfirmExtend061
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
