// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"
)

func init() {
}

// TradeCaptureConfirmExtend060 represents the packet structure.
type TradeCaptureConfirmExtend060 struct {
}

// NewTradeCaptureConfirmExtend060 creates a new instance of TradeCaptureConfirmExtend060.
func NewTradeCaptureConfirmExtend060() *TradeCaptureConfirmExtend060 {
	return &TradeCaptureConfirmExtend060{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureConfirmExtend060) String() string {
	return fmt.Sprintf("TradeCaptureConfirmExtend060{}")
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureConfirmExtend060) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureConfirmExtend060) Decode(buf *bytes.Buffer) error {
	return nil
}
