// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestTradeCaptureReportAckExtend031Codec(t *testing.T) {

	original := &msg.TradeCaptureReportAckExtend031{
		MemberId:               "xxxxxx",
		TraderCode:             "xxxxx",
		CounterPartyMemberId:   "xxxxxx",
		CounterPartyTraderCode: "xxxxx",
		SettlType:              "x",
		SettlPeriod:            "x",
		CashMargin:             "x",
		Memo:                   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.TradeCaptureReportAckExtend031
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
