// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestTradeCaptureReportExtend062Codec(t *testing.T) {

	original := &msg.TradeCaptureReportExtend062{
		CashMargin: "x",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.TradeCaptureReportExtend062
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
