// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"
)

// TradeCaptureReportExtend061 represents the packet structure.
type TradeCaptureReportExtend061 struct {
}

// NewTradeCaptureReportExtend061 creates a new instance of TradeCaptureReportExtend061.
func NewTradeCaptureReportExtend061() *TradeCaptureReportExtend061 {
	return &TradeCaptureReportExtend061{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureReportExtend061) String() string {
	return fmt.Sprintf("TradeCaptureReportExtend061{}")
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureReportExtend061) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureReportExtend061) Decode(buf *bytes.Buffer) error {
	return nil
}
