// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// TradeCaptureReportExtend062 represents the packet structure.
type TradeCaptureReportExtend062 struct {
	CashMargin string `json:"CashMargin"`
}

// NewTradeCaptureReportExtend062 creates a new instance of TradeCaptureReportExtend062.
func NewTradeCaptureReportExtend062() *TradeCaptureReportExtend062 {
	return &TradeCaptureReportExtend062{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureReportExtend062) String() string {
	return fmt.Sprintf("TradeCaptureReportExtend062{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureReportExtend062) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureReportExtend062) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
