// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestTradeCaptureReportCodec(t *testing.T) {

	applExtend := &msg.TradeCaptureReportExtend031{
		MemberId:               "xxxxxx",
		TraderCode:             "xxxxx",
		CounterPartyMemberId:   "xxxxxx",
		CounterPartyTraderCode: "xxxxx",
		SettlType:              "x",
		SettlPeriod:            "x",
		CashMargin:             "x",
		Memo:                   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	original := &msg.TradeCaptureReport{
		SubmittingPbuid:       "xxxxxx",
		SecurityId:            "xxxxxxxx",
		SecurityIdsource:      "xxxx",
		OwnerType:             2,
		ClearingFirm:          "xx",
		TransactTime:          8,
		UserInfo:              "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		TradeReportId:         "xxxxxxxxxx",
		TradeReportType:       1,
		TradeReportTransType:  1,
		TradeHandlingInstr:    "x",
		TradeReportRefId:      "xxxxxxxxxx",
		LastPx:                8,
		LastQty:               8,
		TrdType:               2,
		TrdSubType:            2,
		ConfirmId:             4,
		Side:                  "x",
		Pbuid:                 "xxxxxx",
		AccountId:             "xxxxxxxxxx",
		BranchId:              "xx",
		CounterPartyPbuid:     "xxxxxx",
		CounterPartyAccountId: "xxxxxxxxxx",
		CounterPartyBranchId:  "xx",
		ApplId:                "031",
		ApplExtend:            applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.TradeCaptureReport
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
