// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"
)

func init() {
}

// TradeCaptureCofirmExtend060 represents the packet structure.
type TradeCaptureCofirmExtend060 struct {
}

// NewTradeCaptureCofirmExtend060 creates a new instance of TradeCaptureCofirmExtend060.
func NewTradeCaptureCofirmExtend060() *TradeCaptureCofirmExtend060 {
	return &TradeCaptureCofirmExtend060{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureCofirmExtend060) String() string {
	return fmt.Sprintf("TradeCaptureCofirmExtend060{}")
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureCofirmExtend060) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureCofirmExtend060) Decode(buf *bytes.Buffer) error {
	return nil
}
