// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// TradeCaptureConfirmExtend051 represents the packet structure.
type TradeCaptureConfirmExtend051 struct {
	ExpirationDays uint16 `json:"ExpirationDays"`
	ExpirationType uint8  `json:"ExpirationType"`
	MaturityDate   uint32 `json:"MaturityDate"`
	ShareProperty  string `json:"ShareProperty"`
}

// NewTradeCaptureConfirmExtend051 creates a new instance of TradeCaptureConfirmExtend051.
func NewTradeCaptureConfirmExtend051() *TradeCaptureConfirmExtend051 {
	return &TradeCaptureConfirmExtend051{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureConfirmExtend051) String() string {
	return fmt.Sprintf("TradeCaptureConfirmExtend051{ExpirationDays: %v, ExpirationType: %v, MaturityDate: %v, ShareProperty: %v}", p.ExpirationDays, p.ExpirationType, p.MaturityDate, p.ShareProperty)
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureConfirmExtend051) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicTypeLE(buf, p.ExpirationDays); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationDays", err)
	}
	if err := codec.WriteBasicTypeLE(buf, p.ExpirationType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationType", err)
	}
	if err := codec.WriteBasicTypeLE(buf, p.MaturityDate); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MaturityDate", err)
	}
	if err := codec.WriteFixedString(buf, p.ShareProperty, 2); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureConfirmExtend051) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicTypeLE[uint16](buf); err != nil {
		return err
	} else {
		p.ExpirationDays = val
	}
	if val, err := codec.ReadBasicTypeLE[uint8](buf); err != nil {
		return err
	} else {
		p.ExpirationType = val
	}
	if val, err := codec.ReadBasicTypeLE[uint32](buf); err != nil {
		return err
	} else {
		p.MaturityDate = val
	}
	if val, err := codec.ReadFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ShareProperty = val
	}
	return nil
}
