// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/bjse-trade-bin/messages"
)

func TestTradeCaptureReportAckExtend051Codec(t *testing.T) {

	original := &msg.TradeCaptureReportAckExtend051{
		ExpirationDays: 2,
		ExpirationType: 1,
		ShareProperty:  "xx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.TradeCaptureReportAckExtend051
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
