// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

// TradeCaptureCofirmExtend031 represents the packet structure.
type TradeCaptureCofirmExtend031 struct {
	MemberId               string `json:"MemberID"`
	TraderCode             string `json:"TraderCode"`
	CounterPartyMemberId   string `json:"CounterPartyMemberID"`
	CounterPartyTraderCode string `json:"CounterPartyTraderCode"`
	SettlType              string `json:"SettlType"`
	SettlPeriod            string `json:"SettlPeriod"`
	CashMargin             string `json:"CashMargin"`
	Memo                   string `json:"Memo"`
}

// NewTradeCaptureCofirmExtend031 creates a new instance of TradeCaptureCofirmExtend031.
func NewTradeCaptureCofirmExtend031() *TradeCaptureCofirmExtend031 {
	return &TradeCaptureCofirmExtend031{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureCofirmExtend031) String() string {
	return fmt.Sprintf("TradeCaptureCofirmExtend031{MemberId: %v, TraderCode: %v, CounterPartyMemberId: %v, CounterPartyTraderCode: %v, SettlType: %v, SettlPeriod: %v, CashMargin: %v, Memo: %v}", p.MemberId, p.TraderCode, p.CounterPartyMemberId, p.CounterPartyTraderCode, p.SettlType, p.SettlPeriod, p.CashMargin, p.Memo)
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureCofirmExtend031) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.MemberId, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.TraderCode, 5); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.CounterPartyMemberId, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.CounterPartyTraderCode, 5); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SettlType, 1); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SettlPeriod, 1); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.Memo, 120); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureCofirmExtend031) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.MemberId = val
	}
	if val, err := codec.GetFixedString(buf, 5); err != nil {
		return err
	} else {
		p.TraderCode = val
	}
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.CounterPartyMemberId = val
	}
	if val, err := codec.GetFixedString(buf, 5); err != nil {
		return err
	} else {
		p.CounterPartyTraderCode = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.SettlType = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.SettlPeriod = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	if val, err := codec.GetFixedString(buf, 120); err != nil {
		return err
	} else {
		p.Memo = val
	}
	return nil
}
