// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// TradeCaptureConfirmExtend062 represents the packet structure.
type TradeCaptureConfirmExtend062 struct {
	CashMargin string `json:"CashMargin"`
}

// NewTradeCaptureConfirmExtend062 creates a new instance of TradeCaptureConfirmExtend062.
func NewTradeCaptureConfirmExtend062() *TradeCaptureConfirmExtend062 {
	return &TradeCaptureConfirmExtend062{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureConfirmExtend062) String() string {
	return fmt.Sprintf("TradeCaptureConfirmExtend062{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureConfirmExtend062) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureConfirmExtend062) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
