// Code generated by fin-protoc. DO NOT EDIT.
package bjse_trade_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// TradeCaptureReportAckExtend051 represents the packet structure.
type TradeCaptureReportAckExtend051 struct {
	ExpirationDays uint16 `json:"ExpirationDays"`
	ExpirationType uint8  `json:"ExpirationType"`
	ShareProperty  string `json:"ShareProperty"`
}

// NewTradeCaptureReportAckExtend051 creates a new instance of TradeCaptureReportAckExtend051.
func NewTradeCaptureReportAckExtend051() *TradeCaptureReportAckExtend051 {
	return &TradeCaptureReportAckExtend051{}
}

// String returns a string representation of the packet.
func (p *TradeCaptureReportAckExtend051) String() string {
	return fmt.Sprintf("TradeCaptureReportAckExtend051{ExpirationDays: %v, ExpirationType: %v, ShareProperty: %v}", p.ExpirationDays, p.ExpirationType, p.ShareProperty)
}

// Encode encodes the packet into a byte slice.
func (p *TradeCaptureReportAckExtend051) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicTypeLE(buf, p.ExpirationDays); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationDays", err)
	}
	if err := codec.WriteBasicTypeLE(buf, p.ExpirationType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationType", err)
	}
	if err := codec.WriteFixedString(buf, p.ShareProperty, 2); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *TradeCaptureReportAckExtend051) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicTypeLE[uint16](buf); err != nil {
		return err
	} else {
		p.ExpirationDays = val
	}
	if val, err := codec.ReadBasicTypeLE[uint8](buf); err != nil {
		return err
	} else {
		p.ExpirationType = val
	}
	if val, err := codec.ReadFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ShareProperty = val
	}
	return nil
}
