// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// CancelReject represents the packet structure.
type CancelReject struct {
	Pbu          string `json:"Pbu"`
	SetId        uint32 `json:"SetID"`
	ReportIndex  uint64 `json:"ReportIndex"`
	BizId        uint32 `json:"BizID"`
	BizPbu       string `json:"BizPbu"`
	ClOrdId      string `json:"ClOrdID"`
	SecurityId   string `json:"SecurityID"`
	OrigClOrdId  string `json:"OrigClOrdID"`
	BranchId     string `json:"BranchID"`
	CxlRejReason uint32 `json:"CxlRejReason"`
	TradeDate    uint32 `json:"TradeDate"`
	TransactTime uint64 `json:"TransactTime"`
	UserInfo     string `json:"UserInfo"`
}

// NewCancelReject creates a new instance of CancelReject.
func NewCancelReject() *CancelReject {
	return &CancelReject{}
}

// String returns a string representation of the packet.
func (p *CancelReject) String() string {
	return fmt.Sprintf("CancelReject{Pbu: %v, SetId: %v, ReportIndex: %v, BizId: %v, BizPbu: %v, ClOrdId: %v, SecurityId: %v, OrigClOrdId: %v, BranchId: %v, CxlRejReason: %v, TradeDate: %v, TransactTime: %v, UserInfo: %v}", p.Pbu, p.SetId, p.ReportIndex, p.BizId, p.BizPbu, p.ClOrdId, p.SecurityId, p.OrigClOrdId, p.BranchId, p.CxlRejReason, p.TradeDate, p.TransactTime, p.UserInfo)
}

// Encode encodes the packet into a byte slice.
func (p *CancelReject) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.Pbu, 8); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.SetId); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "SetID", err)
	}
	if err := codec.PutBasicType(buf, p.ReportIndex); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ReportIndex", err)
	}
	if err := codec.PutBasicType(buf, p.BizId); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "BizID", err)
	}
	if err := codec.PutFixedString(buf, p.BizPbu, 8); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.ClOrdId, 10); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SecurityId, 12); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.OrigClOrdId, 10); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.BranchId, 8); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.CxlRejReason); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "CxlRejReason", err)
	}
	if err := codec.PutBasicType(buf, p.TradeDate); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "TradeDate", err)
	}
	if err := codec.PutBasicType(buf, p.TransactTime); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "TransactTime", err)
	}
	if err := codec.PutFixedString(buf, p.UserInfo, 32); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *CancelReject) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.Pbu = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.SetId = val
	}
	if val, err := codec.GetBasicType[uint64](buf); err != nil {
		return err
	} else {
		p.ReportIndex = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.BizId = val
	}
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.BizPbu = val
	}
	if val, err := codec.GetFixedString(buf, 10); err != nil {
		return err
	} else {
		p.ClOrdId = val
	}
	if val, err := codec.GetFixedString(buf, 12); err != nil {
		return err
	} else {
		p.SecurityId = val
	}
	if val, err := codec.GetFixedString(buf, 10); err != nil {
		return err
	} else {
		p.OrigClOrdId = val
	}
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.BranchId = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.CxlRejReason = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.TradeDate = val
	}
	if val, err := codec.GetBasicType[uint64](buf); err != nil {
		return err
	} else {
		p.TransactTime = val
	}
	if val, err := codec.GetFixedString(buf, 32); err != nil {
		return err
	} else {
		p.UserInfo = val
	}
	return nil
}
