// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestCancelRejectCodec(t *testing.T) {

	original := &msg.CancelReject{
		Pbu:          "xxxxxxxx",
		SetId:        4,
		ReportIndex:  8,
		BizId:        4,
		BizPbu:       "xxxxxxxx",
		ClOrdId:      "xxxxxxxxxx",
		SecurityId:   "xxxxxxxxxxxx",
		OrigClOrdId:  "xxxxxxxxxx",
		BranchId:     "xxxxxxxx",
		CxlRejReason: 4,
		TradeDate:    4,
		TransactTime: 8,
		UserInfo:     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.CancelReject
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
