// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestExecRptSyncCodec(t *testing.T) {

	subExecRptSync := &msg.SubExecRptSync{
		Pbu:              "xxxxxxxx",
		SetId:            4,
		BeginReportIndex: 8,
	}
	original := &msg.ExecRptSync{
		SubExecRptSync: []*msg.SubExecRptSync{subExecRptSync},
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.ExecRptSync
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
