// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestExecRptEndOfStreamCodec(t *testing.T) {

	original := &msg.ExecRptEndOfStream{
		Pbu:            "xxxxxxxx",
		SetId:          4,
		EndReportIndex: 8,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.ExecRptEndOfStream
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
