// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestExecRptInfoCodec(t *testing.T) {

	original := &msg.ExecRptInfo{
		PlatformId: 2,
		Pbu:        []string{"xxxxxxxx"},
		SetId:      []uint32{4},
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.ExecRptInfo
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
