// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// PlatformState represents the packet structure.
type PlatformState struct {
	PlatformId    uint16 `json:"PlatformID"`
	PlatformState uint16 `json:"PlatformState"`
}

// NewPlatformState creates a new instance of PlatformState.
func NewPlatformState() *PlatformState {
	return &PlatformState{}
}

// String returns a string representation of the packet.
func (p *PlatformState) String() string {
	return fmt.Sprintf("PlatformState{PlatformId: %v, PlatformState: %v}", p.PlatformId, p.PlatformState)
}

// Encode encodes the packet into a byte slice.
func (p *PlatformState) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutBasicType(buf, p.PlatformId); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "PlatformID", err)
	}
	if err := codec.PutBasicType(buf, p.PlatformState); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "PlatformState", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *PlatformState) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.PlatformId = val
	}
	if val, err := codec.GetBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.PlatformState = val
	}
	return nil
}
