// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestReportCodec(t *testing.T) {

	original := &msg.Report{
		Pbu:           "xxxxxxxx",
		SetId:         4,
		ReportIndex:   8,
		BizId:         4,
		ExecType:      "x",
		BizPbu:        "xxxxxxxx",
		ClOrdId:       "xxxxxxxxxx",
		SecurityId:    "xxxxxxxxxxxx",
		Account:       "xxxxxxxxxxxxx",
		OwnerType:     1,
		Side:          "x",
		Price:         8,
		OrderQty:      8,
		LeavesQty:     8,
		CxlQty:        8,
		OrdType:       "x",
		TimeInForce:   "x",
		OrdStatus:     "x",
		CreditTag:     "xx",
		OrigClOrdId:   "xxxxxxxxxx",
		ClearingFirm:  "xxxxxxxx",
		BranchId:      "xxxxxxxx",
		OrdRejReason:  4,
		OrdCnfmId:     "xxxxxxxxxxxxxxxx",
		OrigOrdCnfmId: "xxxxxxxxxxxxxxxx",
		TradeDate:     4,
		TransactTime:  8,
		UserInfo:      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Report
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
