// Code generated by fin-protoc. DO NOT EDIT.
package sse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sse-bin/messages"
)

func TestReportCodec(t *testing.T) {

	original := &msg.Report{
		Pbu:            "xxxxxxxx",
		SetId:          4,
		ReportIndex:    8,
		BizId:          4,
		ExecType:       "x",
		BizPbu:         "xxxxxxxx",
		ClOrdId:        "xxxxxxxxxx",
		SecurityId:     "xxxxxxxxxxxx",
		Account:        "xxxxxxxxxxxxx",
		OwnerType:      1,
		OrderEntryTime: 8,
		LastPx:         8,
		LastQty:        8,
		GrossTradeAmt:  8,
		Side:           "x",
		OrderQty:       8,
		LeavesQty:      8,
		OrdStatus:      "x",
		CreditTag:      "xx",
		ClearingFirm:   "xxxxxxxx",
		BranchId:       "xxxxxxxx",
		TrdCnfmId:      "xxxxxxxxxxxxxxxx",
		OrdCnfmId:      "xxxxxxxxxxxxxxxx",
		TradeDate:      4,
		TransactTime:   8,
		UserInfo:       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Report
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
