// Code generated by fin-protoc. DO NOT EDIT.
package sample_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sample-bin/messages"
)

func TestBasicPacketCodec(t *testing.T) {

	original := &msg.BasicPacket{
		FieldI8:       1,
		FieldI16:      2,
		FieldI32:      4,
		FieldI64:      8,
		FieldChar:     "x",
		FieldU8:       1,
		FieldU16:      2,
		FieldU32:      4,
		FieldU64:      8,
		FieldF32:      4,
		FieldF64:      8,
		FieldI8List:   []int8{1},
		FieldI16List:  []int16{2},
		FieldI32List:  []int32{4},
		FieldI64List:  []int64{8},
		FieldCharList: []string{"x"},
		FieldU8List:   []uint8{1},
		FieldU16List:  []uint16{2},
		FieldU32List:  []uint32{4},
		FieldU64List:  []uint64{8},
		FieldF32List:  []float32{4},
		FieldF64List:  []float64{8},
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.BasicPacket
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
