// Code generated by fin-protoc. DO NOT EDIT.
package sample_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sample/messages"
)

func TestEmptyPacketCodec(t *testing.T) {

	original := &msg.EmptyPacket{}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.EmptyPacket
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
