// Code generated by fin-protoc. DO NOT EDIT.
package sample_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/sample/messages"
)

func TestNestedPacketCodec(t *testing.T) {

	subPacket := &msg.SubPacket{
		FieldU32:     4,
		FieldI16List: []int16{2},
	}
	subPacketList := &msg.SubPacket{
		FieldU32:     4,
		FieldI16List: []int16{2},
	}
	inerPacket := &msg.InerPacket{
		FieldU32:     4,
		FieldI16List: []int16{2},
	}
	original := &msg.NestedPacket{
		SubPacket:     subPacket,
		SubPacketList: []*msg.SubPacket{subPacketList},
		InerPacket:    inerPacket,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.NestedPacket
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
