// Code generated by fin-protoc. DO NOT EDIT.
package sample_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// RootPacket represents the packet structure.
type RootPacket struct {
	MsgType    uint16            `json:"MsgType"`
	PayloadLen uint32            `json:"PayloadLen"`
	Payload    codec.BinaryCodec `json:"Payload"`
	Checksum   int32             `json:"Checksum"`
}

// NewRootPacket creates a new instance of RootPacket.
func NewRootPacket() *RootPacket {
	return &RootPacket{}
}

// String returns a string representation of the packet.
func (p *RootPacket) String() string {
	return fmt.Sprintf("RootPacket{MsgType: %v, PayloadLen: %v, Payload: %v, Checksum: %v}", p.MsgType, p.PayloadLen, p.Payload, p.Checksum)
}

// Encode encodes the packet into a byte slice.
func (p *RootPacket) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *RootPacket) Decode(buf *bytes.Buffer) error {
	// Implement decoding logic here.
	return nil
}
