// Code generated by fin-protoc. DO NOT EDIT.
package sample_bin

// SubPacket represents the packet structure.

// Encode encodes the packet into a byte slice.

// Decode decodes the packet from a byte slice.
