// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestBusinessRejectCodec(t *testing.T) {

	original := &msg.BusinessReject{
		ApplId:               "xxx",
		TransactTime:         8,
		SubmittingPbuid:      "xxxxxx",
		SecurityId:           "xxxxxxxx",
		SecurityIdsource:     "xxxx",
		RefSeqNum:            8,
		RefMsgType:           4,
		BusinessRejectRefId:  "xxxxxxxxxx",
		BusinessRejectReason: 2,
		BusinessRejectText:   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.BusinessReject
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
