// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestCancelRejectCodec(t *testing.T) {

	original := &msg.CancelReject{
		PartitionNo:      4,
		ReportIndex:      8,
		ApplId:           "xxx",
		ReportingPbuid:   "xxxxxx",
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxx",
		ClOrdId:          "xxxxxxxxxx",
		OrigClOrdId:      "xxxxxxxxxx",
		Side:             "x",
		OrdStatus:        "x",
		CxlRejReason:     2,
		RejectText:       "xxxxxxxxxxxxxxxx",
		OrderId:          "xxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.CancelReject
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
