// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
	RegistryExecutionReportApplIdFactory("010", func() codec.BinaryCodec { return &Extend200115{} })
	RegistryExecutionReportApplIdFactory("020", func() codec.BinaryCodec { return &Extend200215{} })
	RegistryExecutionReportApplIdFactory("030", func() codec.BinaryCodec { return &Extend200315{} })
	RegistryExecutionReportApplIdFactory("051", func() codec.BinaryCodec { return &Extend200515{} })
	RegistryExecutionReportApplIdFactory("052", func() codec.BinaryCodec { return &Extend200515{} })
	RegistryExecutionReportApplIdFactory("056", func() codec.BinaryCodec { return &Extend200515{} })
	RegistryExecutionReportApplIdFactory("057", func() codec.BinaryCodec { return &Extend200515{} })
	RegistryExecutionReportApplIdFactory("060", func() codec.BinaryCodec { return &Extend200615{} })
	RegistryExecutionReportApplIdFactory("061", func() codec.BinaryCodec { return &Extend200615{} })
	RegistryExecutionReportApplIdFactory("070", func() codec.BinaryCodec { return &Extend200715{} })
	RegistryExecutionReportApplIdFactory("630", func() codec.BinaryCodec { return &Extend206315{} })
	RegistryExecutionReportApplIdFactory("370", func() codec.BinaryCodec { return &Extend203715{} })
	RegistryExecutionReportApplIdFactory("410", func() codec.BinaryCodec { return &Extend204115{} })
	RegistryExecutionReportApplIdFactory("412", func() codec.BinaryCodec { return &Extend204115{} })
	RegistryExecutionReportApplIdFactory("413", func() codec.BinaryCodec { return &Extend204115{} })
	RegistryExecutionReportApplIdFactory("415", func() codec.BinaryCodec { return &Extend204115{} })
	RegistryExecutionReportApplIdFactory("416", func() codec.BinaryCodec { return &Extend204115{} })
	RegistryExecutionReportApplIdFactory("417", func() codec.BinaryCodec { return &Extend204130{} })
	RegistryExecutionReportApplIdFactory("470", func() codec.BinaryCodec { return &Extend204715{} })
}

var executionReportApplIdFactoryCache = map[string]func() codec.BinaryCodec{}

func RegistryExecutionReportApplIdFactory(applId string, factory func() codec.BinaryCodec) {
	executionReportApplIdFactoryCache[applId] = factory
}

func NewExecutionReportMessageByApplId(key string) (codec.BinaryCodec, error) {
	if factory, ok := executionReportApplIdFactoryCache[key]; ok {
		return factory(), nil
	}
	return nil, fmt.Errorf("unknown message type")
}

// ExecutionReport represents the packet structure.
type ExecutionReport struct {
	PartitionNo      int32             `json:"PartitionNo"`
	ReportIndex      int64             `json:"ReportIndex"`
	ApplId           string            `json:"ApplID"`
	ReportingPbuid   string            `json:"ReportingPBUID"`
	SubmittingPbuid  string            `json:"SubmittingPBUID"`
	SecurityId       string            `json:"SecurityID"`
	SecurityIdsource string            `json:"SecurityIDSource"`
	OwnerType        uint16            `json:"OwnerType"`
	ClearingFirm     string            `json:"ClearingFirm"`
	TransactTime     int64             `json:"TransactTime"`
	UserInfo         string            `json:"UserInfo"`
	OrderId          string            `json:"OrderID"`
	ClOrdId          string            `json:"ClOrdID"`
	QuoteMsgId       string            `json:"QuoteMsgID"`
	ExecId           string            `json:"ExecID"`
	ExecType         string            `json:"ExecType"`
	OrdStatus        string            `json:"OrdStatus"`
	LastPx           int64             `json:"LastPx"`
	LastQty          int64             `json:"LastQty"`
	LeavesQty        int64             `json:"LeavesQty"`
	CumQty           int64             `json:"CumQty"`
	Side             string            `json:"Side"`
	AccountId        string            `json:"AccountID"`
	BranchId         string            `json:"BranchID"`
	ApplExtend       codec.BinaryCodec `json:"ApplExtend"`
}

// NewExecutionReport creates a new instance of ExecutionReport.
func NewExecutionReport() *ExecutionReport {
	return &ExecutionReport{}
}

// String returns a string representation of the packet.
func (p *ExecutionReport) String() string {
	return fmt.Sprintf("ExecutionReport{PartitionNo: %v, ReportIndex: %v, ApplId: %v, ReportingPbuid: %v, SubmittingPbuid: %v, SecurityId: %v, SecurityIdsource: %v, OwnerType: %v, ClearingFirm: %v, TransactTime: %v, UserInfo: %v, OrderId: %v, ClOrdId: %v, QuoteMsgId: %v, ExecId: %v, ExecType: %v, OrdStatus: %v, LastPx: %v, LastQty: %v, LeavesQty: %v, CumQty: %v, Side: %v, AccountId: %v, BranchId: %v, ApplExtend: %v}", p.PartitionNo, p.ReportIndex, p.ApplId, p.ReportingPbuid, p.SubmittingPbuid, p.SecurityId, p.SecurityIdsource, p.OwnerType, p.ClearingFirm, p.TransactTime, p.UserInfo, p.OrderId, p.ClOrdId, p.QuoteMsgId, p.ExecId, p.ExecType, p.OrdStatus, p.LastPx, p.LastQty, p.LeavesQty, p.CumQty, p.Side, p.AccountId, p.BranchId, p.ApplExtend)
}

// Encode encodes the packet into a byte slice.
func (p *ExecutionReport) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicType(buf, p.PartitionNo); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "PartitionNo", err)
	}
	if err := codec.WriteBasicType(buf, p.ReportIndex); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ReportIndex", err)
	}
	if err := codec.WriteFixedString(buf, p.ApplId, 3); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.ReportingPbuid, 6); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.SubmittingPbuid, 6); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.SecurityId, 8); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.SecurityIdsource, 4); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.OwnerType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "OwnerType", err)
	}
	if err := codec.WriteFixedString(buf, p.ClearingFirm, 2); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.TransactTime); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "TransactTime", err)
	}
	if err := codec.WriteFixedString(buf, p.UserInfo, 8); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.OrderId, 16); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.ClOrdId, 10); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.QuoteMsgId, 10); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.ExecId, 16); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.ExecType, 1); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.OrdStatus, 1); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.LastPx); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "LastPx", err)
	}
	if err := codec.WriteBasicType(buf, p.LastQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "LastQty", err)
	}
	if err := codec.WriteBasicType(buf, p.LeavesQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "LeavesQty", err)
	}
	if err := codec.WriteBasicType(buf, p.CumQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "CumQty", err)
	}
	if err := codec.WriteFixedString(buf, p.Side, 1); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.AccountId, 12); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.BranchId, 4); err != nil {
		return err
	}
	if p.ApplExtend == nil {
		if val, err := NewExecutionReportMessageByApplId(p.ApplId); err != nil {
			return err
		} else {
			p.ApplExtend = val
		}
	}
	if err := p.ApplExtend.Encode(buf); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *ExecutionReport) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicType[int32](buf); err != nil {
		return err
	} else {
		p.PartitionNo = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.ReportIndex = val
	}
	if val, err := codec.ReadFixedString(buf, 3); err != nil {
		return err
	} else {
		p.ApplId = val
	}
	if val, err := codec.ReadFixedString(buf, 6); err != nil {
		return err
	} else {
		p.ReportingPbuid = val
	}
	if val, err := codec.ReadFixedString(buf, 6); err != nil {
		return err
	} else {
		p.SubmittingPbuid = val
	}
	if val, err := codec.ReadFixedString(buf, 8); err != nil {
		return err
	} else {
		p.SecurityId = val
	}
	if val, err := codec.ReadFixedString(buf, 4); err != nil {
		return err
	} else {
		p.SecurityIdsource = val
	}
	if val, err := codec.ReadBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.OwnerType = val
	}
	if val, err := codec.ReadFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ClearingFirm = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.TransactTime = val
	}
	if val, err := codec.ReadFixedString(buf, 8); err != nil {
		return err
	} else {
		p.UserInfo = val
	}
	if val, err := codec.ReadFixedString(buf, 16); err != nil {
		return err
	} else {
		p.OrderId = val
	}
	if val, err := codec.ReadFixedString(buf, 10); err != nil {
		return err
	} else {
		p.ClOrdId = val
	}
	if val, err := codec.ReadFixedString(buf, 10); err != nil {
		return err
	} else {
		p.QuoteMsgId = val
	}
	if val, err := codec.ReadFixedString(buf, 16); err != nil {
		return err
	} else {
		p.ExecId = val
	}
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.ExecType = val
	}
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.OrdStatus = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.LastPx = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.LastQty = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.LeavesQty = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.CumQty = val
	}
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.Side = val
	}
	if val, err := codec.ReadFixedString(buf, 12); err != nil {
		return err
	} else {
		p.AccountId = val
	}
	if val, err := codec.ReadFixedString(buf, 4); err != nil {
		return err
	} else {
		p.BranchId = val
	}
	if val, err := NewExecutionReportMessageByApplId(p.ApplId); err != nil {
		return err
	} else {
		p.ApplExtend = val
	}
	if err := p.ApplExtend.Decode(buf); err != nil {
		return err
	}
	return nil
}
