// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestExecutionConfirmCodec(t *testing.T) {

	applExtend := &msg.Extend200102{
		StopPx:         8,
		MinQty:         8,
		MaxPriceLevels: 2,
		TimeInForce:    "x",
		CashMargin:     "x",
	}
	original := &msg.ExecutionConfirm{
		PartitionNo:       4,
		ReportIndex:       8,
		ReportingPbuid:    "xxxxxx",
		SubmittingPbuid:   "xxxxxx",
		SecurityId:        "xxxxxxxx",
		SecurityIdsource:  "xxxx",
		OwnerType:         2,
		ClearingFirm:      "xx",
		TransactTime:      8,
		UserInfo:          "xxxxxxxx",
		OrderId:           "xxxxxxxxxxxxxxxx",
		ClOrdId:           "xxxxxxxxxx",
		QuoteMsgId:        "xxxxxxxxxx",
		OrigClOrdId:       "xxxxxxxxxx",
		ExecId:            "xxxxxxxxxxxxxxxx",
		ExecType:          "x",
		OrdStatus:         "x",
		OrdRejReason:      2,
		LeavesQty:         8,
		CumQty:            8,
		Side:              "x",
		OrdType:           "x",
		OrderQty:          8,
		Price:             8,
		AccountId:         "xxxxxxxxxxxx",
		BranchId:          "xxxx",
		OrderRestrictions: "xxxx",
		ApplId:            "010",
		ApplExtend:        applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.ExecutionConfirm
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
