// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestExecutionReportCodec(t *testing.T) {

	applExtend := &msg.Extend200115{
		CashMargin: "x",
	}
	original := &msg.ExecutionReport{
		PartitionNo:      4,
		ReportIndex:      8,
		ReportingPbuid:   "xxxxxx",
		SubmittingPbuid:  "xxxxxx",
		SecurityId:       "xxxxxxxx",
		SecurityIdsource: "xxxx",
		OwnerType:        2,
		ClearingFirm:     "xx",
		TransactTime:     8,
		UserInfo:         "xxxxxxxx",
		OrderId:          "xxxxxxxxxxxxxxxx",
		ClOrdId:          "xxxxxxxxxx",
		QuoteMsgId:       "xxxxxxxxxx",
		ExecId:           "xxxxxxxxxxxxxxxx",
		ExecType:         "x",
		OrdStatus:        "x",
		LastPx:           8,
		LastQty:          8,
		LeavesQty:        8,
		CumQty:           8,
		Side:             "x",
		AccountId:        "xxxxxxxxxxxx",
		BranchId:         "xxxx",
		ApplId:           "010",
		ApplExtend:       applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.ExecutionReport
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
