// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend201202 represents the packet structure.
type Extend201202 struct {
	InsufficientSecurityId     string `json:"InsufficientSecurityID"`
	NoSecurity                 uint32 `json:"NoSecurity"`
	UnderlyingSecurityId       string `json:"UnderlyingSecurityID"`
	UnderlyingSecurityIdsource string `json:"UnderlyingSecurityIDSource"`
	DeliveryQty                int64  `json:"DeliveryQty"`
	SubstCash                  int64  `json:"SubstCash"`
}

// NewExtend201202 creates a new instance of Extend201202.
func NewExtend201202() *Extend201202 {
	return &Extend201202{}
}

// String returns a string representation of the packet.
func (p *Extend201202) String() string {
	return fmt.Sprintf("Extend201202{InsufficientSecurityId: %v, NoSecurity: %v, UnderlyingSecurityId: %v, UnderlyingSecurityIdsource: %v, DeliveryQty: %v, SubstCash: %v}", p.InsufficientSecurityId, p.NoSecurity, p.UnderlyingSecurityId, p.UnderlyingSecurityIdsource, p.DeliveryQty, p.SubstCash)
}

// Encode encodes the packet into a byte slice.
func (p *Extend201202) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteFixedString(buf, p.InsufficientSecurityId, 8); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.NoSecurity); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "NoSecurity", err)
	}
	if err := codec.WriteFixedString(buf, p.UnderlyingSecurityId, 8); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.UnderlyingSecurityIdsource, 4); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.DeliveryQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "DeliveryQty", err)
	}
	if err := codec.WriteBasicType(buf, p.SubstCash); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "SubstCash", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend201202) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadFixedString(buf, 8); err != nil {
		return err
	} else {
		p.InsufficientSecurityId = val
	}
	if val, err := codec.ReadBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.NoSecurity = val
	}
	if val, err := codec.ReadFixedString(buf, 8); err != nil {
		return err
	} else {
		p.UnderlyingSecurityId = val
	}
	if val, err := codec.ReadFixedString(buf, 4); err != nil {
		return err
	} else {
		p.UnderlyingSecurityIdsource = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.DeliveryQty = val
	}
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.SubstCash = val
	}
	return nil
}
