// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend201602 represents the packet structure.
type Extend201602 struct {
	ContractAccountCode string `json:"ContractAccountCode"`
}

// NewExtend201602 creates a new instance of Extend201602.
func NewExtend201602() *Extend201602 {
	return &Extend201602{}
}

// String returns a string representation of the packet.
func (p *Extend201602) String() string {
	return fmt.Sprintf("Extend201602{ContractAccountCode: %v}", p.ContractAccountCode)
}

// Encode encodes the packet into a byte slice.
func (p *Extend201602) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.ContractAccountCode, 6); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend201602) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.ContractAccountCode = val
	}
	return nil
}
