// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestExtend206302Codec(t *testing.T) {

	original := &msg.Extend206302{
		RejectText:       "xxxxxxxxxxxxxxxx",
		StopPx:           8,
		MinQty:           8,
		MaxPriceLevels:   2,
		TimeInForce:      "x",
		LotType:          "x",
		ImcrejectTextLen: 4,
		ImcrejectText:    "hello",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Extend206302
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
