// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

// Extend200702 represents the packet structure.
type Extend200702 struct {
	ExpirationDays uint16 `json:"ExpirationDays"`
	ExpirationType uint8  `json:"ExpirationType"`
	ShareProperty  string `json:"ShareProperty"`
}

// NewExtend200702 creates a new instance of Extend200702.
func NewExtend200702() *Extend200702 {
	return &Extend200702{}
}

// String returns a string representation of the packet.
func (p *Extend200702) String() string {
	return fmt.Sprintf("Extend200702{ExpirationDays: %v, ExpirationType: %v, ShareProperty: %v}", p.ExpirationDays, p.ExpirationType, p.ShareProperty)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200702) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutBasicType(buf, p.ExpirationDays); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationDays", err)
	}
	if err := codec.PutBasicType(buf, p.ExpirationType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationType", err)
	}
	if err := codec.PutFixedString(buf, p.ShareProperty, 2); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200702) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.ExpirationDays = val
	}
	if val, err := codec.GetBasicType[uint8](buf); err != nil {
		return err
	} else {
		p.ExpirationType = val
	}
	if val, err := codec.GetFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ShareProperty = val
	}
	return nil
}
