// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend100501 represents the packet structure.
type Extend100501 struct {
	ConfirmId  string `json:"ConfirmID"`
	CashMargin string `json:"CashMargin"`
}

// NewExtend100501 creates a new instance of Extend100501.
func NewExtend100501() *Extend100501 {
	return &Extend100501{}
}

// String returns a string representation of the packet.
func (p *Extend100501) String() string {
	return fmt.Sprintf("Extend100501{ConfirmId: %v, CashMargin: %v}", p.ConfirmId, p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend100501) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteFixedString(buf, p.ConfirmId, 8); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend100501) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadFixedString(buf, 8); err != nil {
		return err
	} else {
		p.ConfirmId = val
	}
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
