// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend202802 represents the packet structure.
type Extend202802 struct {
	LenderPbu       string `json:"LenderPBU"`
	LenderAccountId string `json:"LenderAccountID"`
}

// NewExtend202802 creates a new instance of Extend202802.
func NewExtend202802() *Extend202802 {
	return &Extend202802{}
}

// String returns a string representation of the packet.
func (p *Extend202802) String() string {
	return fmt.Sprintf("Extend202802{LenderPbu: %v, LenderAccountId: %v}", p.LenderPbu, p.LenderAccountId)
}

// Encode encodes the packet into a byte slice.
func (p *Extend202802) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.LenderPbu, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.LenderAccountId, 12); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend202802) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.LenderPbu = val
	}
	if val, err := codec.GetFixedString(buf, 12); err != nil {
		return err
	} else {
		p.LenderAccountId = val
	}
	return nil
}
