// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend200502 represents the packet structure.
type Extend200502 struct {
	ConfirmId  string `json:"ConfirmID"`
	CashMargin string `json:"CashMargin"`
}

// NewExtend200502 creates a new instance of Extend200502.
func NewExtend200502() *Extend200502 {
	return &Extend200502{}
}

// String returns a string representation of the packet.
func (p *Extend200502) String() string {
	return fmt.Sprintf("Extend200502{ConfirmId: %v, CashMargin: %v}", p.ConfirmId, p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200502) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.ConfirmId, 8); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200502) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.ConfirmId = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
