// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend202902 represents the packet structure.
type Extend202902 struct {
	DeductionPbu       string `json:"DeductionPBU"`
	DeductionAccountId string `json:"DeductionAccountID"`
}

// NewExtend202902 creates a new instance of Extend202902.
func NewExtend202902() *Extend202902 {
	return &Extend202902{}
}

// String returns a string representation of the packet.
func (p *Extend202902) String() string {
	return fmt.Sprintf("Extend202902{DeductionPbu: %v, DeductionAccountId: %v}", p.DeductionPbu, p.DeductionAccountId)
}

// Encode encodes the packet into a byte slice.
func (p *Extend202902) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.DeductionPbu, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.DeductionAccountId, 12); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend202902) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.DeductionPbu = val
	}
	if val, err := codec.GetFixedString(buf, 12); err != nil {
		return err
	} else {
		p.DeductionAccountId = val
	}
	return nil
}
