// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend101701 represents the packet structure.
type Extend101701 struct {
	CashOrderQty int64 `json:"CashOrderQty"`
}

// NewExtend101701 creates a new instance of Extend101701.
func NewExtend101701() *Extend101701 {
	return &Extend101701{}
}

// String returns a string representation of the packet.
func (p *Extend101701) String() string {
	return fmt.Sprintf("Extend101701{CashOrderQty: %v}", p.CashOrderQty)
}

// Encode encodes the packet into a byte slice.
func (p *Extend101701) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicType(buf, p.CashOrderQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "CashOrderQty", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend101701) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicType[int64](buf); err != nil {
		return err
	} else {
		p.CashOrderQty = val
	}
	return nil
}
