// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend200715 represents the packet structure.
type Extend200715 struct {
	ExpirationDays uint16 `json:"ExpirationDays"`
	ExpirationType uint8  `json:"ExpirationType"`
	MaturityDate   uint32 `json:"MaturityDate"`
	ShareProperty  string `json:"ShareProperty"`
}

// NewExtend200715 creates a new instance of Extend200715.
func NewExtend200715() *Extend200715 {
	return &Extend200715{}
}

// String returns a string representation of the packet.
func (p *Extend200715) String() string {
	return fmt.Sprintf("Extend200715{ExpirationDays: %v, ExpirationType: %v, MaturityDate: %v, ShareProperty: %v}", p.ExpirationDays, p.ExpirationType, p.MaturityDate, p.ShareProperty)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200715) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicType(buf, p.ExpirationDays); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationDays", err)
	}
	if err := codec.WriteBasicType(buf, p.ExpirationType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "ExpirationType", err)
	}
	if err := codec.WriteBasicType(buf, p.MaturityDate); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MaturityDate", err)
	}
	if err := codec.WriteFixedString(buf, p.ShareProperty, 2); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200715) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.ExpirationDays = val
	}
	if val, err := codec.ReadBasicType[uint8](buf); err != nil {
		return err
	} else {
		p.ExpirationType = val
	}
	if val, err := codec.ReadBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.MaturityDate = val
	}
	if val, err := codec.ReadFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ShareProperty = val
	}
	return nil
}
