// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend100601 represents the packet structure.
type Extend100601 struct {
	CashMargin string `json:"CashMargin"`
}

// NewExtend100601 creates a new instance of Extend100601.
func NewExtend100601() *Extend100601 {
	return &Extend100601{}
}

// String returns a string representation of the packet.
func (p *Extend100601) String() string {
	return fmt.Sprintf("Extend100601{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend100601) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend100601) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
