// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend200315 represents the packet structure.
type Extend200315 struct {
	MaturityDate uint32 `json:"MaturityDate"`
}

// NewExtend200315 creates a new instance of Extend200315.
func NewExtend200315() *Extend200315 {
	return &Extend200315{}
}

// String returns a string representation of the packet.
func (p *Extend200315) String() string {
	return fmt.Sprintf("Extend200315{MaturityDate: %v}", p.MaturityDate)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200315) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicType(buf, p.MaturityDate); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MaturityDate", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200315) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.MaturityDate = val
	}
	return nil
}
