// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend206315 represents the packet structure.
type Extend206315 struct {
	CashMargin string `json:"CashMargin"`
}

// NewExtend206315 creates a new instance of Extend206315.
func NewExtend206315() *Extend206315 {
	return &Extend206315{}
}

// String returns a string representation of the packet.
func (p *Extend206315) String() string {
	return fmt.Sprintf("Extend206315{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend206315) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend206315) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
