// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestExtend200202Codec(t *testing.T) {

	original := &msg.Extend200202{
		StopPx:         8,
		MinQty:         8,
		MaxPriceLevels: 2,
		TimeInForce:    "x",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Extend200202
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
