// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

// Extend200415 represents the packet structure.
type Extend200415 struct {
	PositionEffect      string `json:"PositionEffect"`
	CoveredOrUncovered  uint8  `json:"CoveredOrUncovered"`
	ContractAccountCode string `json:"ContractAccountCode"`
	SecondaryOrderId    string `json:"SecondaryOrderID"`
}

// NewExtend200415 creates a new instance of Extend200415.
func NewExtend200415() *Extend200415 {
	return &Extend200415{}
}

// String returns a string representation of the packet.
func (p *Extend200415) String() string {
	return fmt.Sprintf("Extend200415{PositionEffect: %v, CoveredOrUncovered: %v, ContractAccountCode: %v, SecondaryOrderId: %v}", p.PositionEffect, p.CoveredOrUncovered, p.ContractAccountCode, p.SecondaryOrderId)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200415) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.PositionEffect, 1); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.CoveredOrUncovered); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "CoveredOrUncovered", err)
	}
	if err := codec.PutFixedString(buf, p.ContractAccountCode, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SecondaryOrderId, 16); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200415) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.PositionEffect = val
	}
	if val, err := codec.GetBasicType[uint8](buf); err != nil {
		return err
	} else {
		p.CoveredOrUncovered = val
	}
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.ContractAccountCode = val
	}
	if val, err := codec.GetFixedString(buf, 16); err != nil {
		return err
	} else {
		p.SecondaryOrderId = val
	}
	return nil
}
