// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend103501 represents the packet structure.
type Extend103501 struct {
	ContractAccountCode string `json:"ContractAccountCode"`
}

// NewExtend103501 creates a new instance of Extend103501.
func NewExtend103501() *Extend103501 {
	return &Extend103501{}
}

// String returns a string representation of the packet.
func (p *Extend103501) String() string {
	return fmt.Sprintf("Extend103501{ContractAccountCode: %v}", p.ContractAccountCode)
}

// Encode encodes the packet into a byte slice.
func (p *Extend103501) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.ContractAccountCode, 6); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend103501) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.ContractAccountCode = val
	}
	return nil
}
