// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

// Extend201502 represents the packet structure.
type Extend201502 struct {
	ShareProperty string `json:"ShareProperty"`
}

// NewExtend201502 creates a new instance of Extend201502.
func NewExtend201502() *Extend201502 {
	return &Extend201502{}
}

// String returns a string representation of the packet.
func (p *Extend201502) String() string {
	return fmt.Sprintf("Extend201502{ShareProperty: %v}", p.ShareProperty)
}

// Encode encodes the packet into a byte slice.
func (p *Extend201502) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.ShareProperty, 2); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend201502) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ShareProperty = val
	}
	return nil
}
