// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend203702 represents the packet structure.
type Extend203702 struct {
	CashMargin string `json:"CashMargin"`
}

// NewExtend203702 creates a new instance of Extend203702.
func NewExtend203702() *Extend203702 {
	return &Extend203702{}
}

// String returns a string representation of the packet.
func (p *Extend203702) String() string {
	return fmt.Sprintf("Extend203702{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend203702) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend203702) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
