// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend106301 represents the packet structure.
type Extend106301 struct {
	StopPx         int64  `json:"StopPx"`
	MinQty         int64  `json:"MinQty"`
	MaxPriceLevels uint16 `json:"MaxPriceLevels"`
	TimeInForce    string `json:"TimeInForce"`
	LotType        string `json:"LotType"`
}

// NewExtend106301 creates a new instance of Extend106301.
func NewExtend106301() *Extend106301 {
	return &Extend106301{}
}

// String returns a string representation of the packet.
func (p *Extend106301) String() string {
	return fmt.Sprintf("Extend106301{StopPx: %v, MinQty: %v, MaxPriceLevels: %v, TimeInForce: %v, LotType: %v}", p.StopPx, p.MinQty, p.MaxPriceLevels, p.TimeInForce, p.LotType)
}

// Encode encodes the packet into a byte slice.
func (p *Extend106301) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutBasicType(buf, p.StopPx); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "StopPx", err)
	}
	if err := codec.PutBasicType(buf, p.MinQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MinQty", err)
	}
	if err := codec.PutBasicType(buf, p.MaxPriceLevels); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MaxPriceLevels", err)
	}
	if err := codec.PutFixedString(buf, p.TimeInForce, 1); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.LotType, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend106301) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetBasicType[int64](buf); err != nil {
		return err
	} else {
		p.StopPx = val
	}
	if val, err := codec.GetBasicType[int64](buf); err != nil {
		return err
	} else {
		p.MinQty = val
	}
	if val, err := codec.GetBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.MaxPriceLevels = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.TimeInForce = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.LotType = val
	}
	return nil
}
