// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// Extend200615 represents the packet structure.
type Extend200615 struct {
	CashMargin string `json:"CashMargin"`
}

// NewExtend200615 creates a new instance of Extend200615.
func NewExtend200615() *Extend200615 {
	return &Extend200615{}
}

// String returns a string representation of the packet.
func (p *Extend200615) String() string {
	return fmt.Sprintf("Extend200615{CashMargin: %v}", p.CashMargin)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200615) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.CashMargin, 1); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200615) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.CashMargin = val
	}
	return nil
}
