// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

// Extend104701 represents the packet structure.
type Extend104701 struct {
	SecondaryOrderId string `json:"SecondaryOrderID"`
}

// NewExtend104701 creates a new instance of Extend104701.
func NewExtend104701() *Extend104701 {
	return &Extend104701{}
}

// String returns a string representation of the packet.
func (p *Extend104701) String() string {
	return fmt.Sprintf("Extend104701{SecondaryOrderId: %v}", p.SecondaryOrderId)
}

// Encode encodes the packet into a byte slice.
func (p *Extend104701) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.SecondaryOrderId, 16); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend104701) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 16); err != nil {
		return err
	} else {
		p.SecondaryOrderId = val
	}
	return nil
}
