// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestExtend204129Codec(t *testing.T) {

	original := &msg.Extend204129{
		MemberId:          "xxxxxx",
		InvestorType:      "xx",
		InvestorId:        "xxxxxxxxxx",
		InvestorName:      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		TraderCode:        "xxxxxxxx",
		SecondaryOrderId:  "xxxxxxxxxxxxxxxx",
		BidTransType:      2,
		BidExecInstType:   2,
		LowLimitPrice:     8,
		HighLimitPrice:    8,
		MinQty:            8,
		TradeDate:         4,
		SettlType:         2,
		SettlPeriod:       1,
		PreTradeAnonymity: 1,
		CashMargin:        "x",
		Memo:              "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Extend204129
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
