// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend200215 represents the packet structure.
type Extend200215 struct {
	MaturityDate uint32 `json:"MaturityDate"`
}

// NewExtend200215 creates a new instance of Extend200215.
func NewExtend200215() *Extend200215 {
	return &Extend200215{}
}

// String returns a string representation of the packet.
func (p *Extend200215) String() string {
	return fmt.Sprintf("Extend200215{MaturityDate: %v}", p.MaturityDate)
}

// Encode encodes the packet into a byte slice.
func (p *Extend200215) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutBasicType(buf, p.MaturityDate); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MaturityDate", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend200215) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.MaturityDate = val
	}
	return nil
}
