// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// Extend201802 represents the packet structure.
type Extend201802 struct {
	Tenderer string `json:"Tenderer"`
}

// NewExtend201802 creates a new instance of Extend201802.
func NewExtend201802() *Extend201802 {
	return &Extend201802{}
}

// String returns a string representation of the packet.
func (p *Extend201802) String() string {
	return fmt.Sprintf("Extend201802{Tenderer: %v}", p.Tenderer)
}

// Encode encodes the packet into a byte slice.
func (p *Extend201802) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.Tenderer, 6); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Extend201802) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.Tenderer = val
	}
	return nil
}
