// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"
)

// Heartbeat represents the packet structure.
type Heartbeat struct {
}

// NewHeartbeat creates a new instance of Heartbeat.
func NewHeartbeat() *Heartbeat {
	return &Heartbeat{}
}

// String returns a string representation of the packet.
func (p *Heartbeat) String() string {
	return fmt.Sprintf("Heartbeat{}")
}

// Encode encodes the packet into a byte slice.
func (p *Heartbeat) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *Heartbeat) Decode(buf *bytes.Buffer) error {
	return nil
}
