// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestLogonCodec(t *testing.T) {

	original := &msg.Logon{
		SenderCompId:     "xxxxxxxxxxxxxxxxxxxx",
		TargetCompId:     "xxxxxxxxxxxxxxxxxxxx",
		HeartBtint:       4,
		Password:         "xxxxxxxxxxxxxxxx",
		DefaultApplVerId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.Logon
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
