// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// NewOrder represents the packet structure.
type NewOrder struct {
	ApplId            string            `json:"ApplID"`
	SubmittingPbuid   string            `json:"SubmittingPBUID"`
	SecurityId        string            `json:"SecurityID"`
	SecurityIdsource  string            `json:"SecurityIDSource"`
	OwnerType         uint16            `json:"OwnerType"`
	ClearingFirm      string            `json:"ClearingFirm"`
	TransactTime      int64             `json:"TransactTime"`
	UserInfo          string            `json:"UserInfo"`
	ClOrdId           string            `json:"ClOrdID"`
	AccountId         string            `json:"AccountID"`
	BranchId          string            `json:"BranchID"`
	OrderRestrictions string            `json:"OrderRestrictions"`
	Side              string            `json:"Side"`
	OrdType           string            `json:"OrdType"`
	OrderQty          int64             `json:"OrderQty"`
	Price             int64             `json:"Price"`
	ApplExtend        codec.BinaryCodec `json:"ApplExtend"`
}

// NewNewOrder creates a new instance of NewOrder.
func NewNewOrder() *NewOrder {
	return &NewOrder{}
}

// String returns a string representation of the packet.
func (p *NewOrder) String() string {
	return fmt.Sprintf("NewOrder{ApplId: %v, SubmittingPbuid: %v, SecurityId: %v, SecurityIdsource: %v, OwnerType: %v, ClearingFirm: %v, TransactTime: %v, UserInfo: %v, ClOrdId: %v, AccountId: %v, BranchId: %v, OrderRestrictions: %v, Side: %v, OrdType: %v, OrderQty: %v, Price: %v, ApplExtend: %v}", p.ApplId, p.SubmittingPbuid, p.SecurityId, p.SecurityIdsource, p.OwnerType, p.ClearingFirm, p.TransactTime, p.UserInfo, p.ClOrdId, p.AccountId, p.BranchId, p.OrderRestrictions, p.Side, p.OrdType, p.OrderQty, p.Price, p.ApplExtend)
}

// Encode encodes the packet into a byte slice.
func (p *NewOrder) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutFixedString(buf, p.ApplId, 3); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SubmittingPbuid, 6); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SecurityId, 8); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.SecurityIdsource, 4); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.OwnerType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "OwnerType", err)
	}
	if err := codec.PutFixedString(buf, p.ClearingFirm, 2); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.TransactTime); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "TransactTime", err)
	}
	if err := codec.PutFixedString(buf, p.UserInfo, 8); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.ClOrdId, 10); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.AccountId, 12); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.BranchId, 4); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.OrderRestrictions, 4); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.Side, 1); err != nil {
		return err
	}
	if err := codec.PutFixedString(buf, p.OrdType, 1); err != nil {
		return err
	}
	if err := codec.PutBasicType(buf, p.OrderQty); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "OrderQty", err)
	}
	if err := codec.PutBasicType(buf, p.Price); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "Price", err)
	}
	if err := p.ApplExtend.Encode(buf); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *NewOrder) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetFixedString(buf, 3); err != nil {
		return err
	} else {
		p.ApplId = val
	}
	if val, err := codec.GetFixedString(buf, 6); err != nil {
		return err
	} else {
		p.SubmittingPbuid = val
	}
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.SecurityId = val
	}
	if val, err := codec.GetFixedString(buf, 4); err != nil {
		return err
	} else {
		p.SecurityIdsource = val
	}
	if val, err := codec.GetBasicType[uint16](buf); err != nil {
		return err
	} else {
		p.OwnerType = val
	}
	if val, err := codec.GetFixedString(buf, 2); err != nil {
		return err
	} else {
		p.ClearingFirm = val
	}
	if val, err := codec.GetBasicType[int64](buf); err != nil {
		return err
	} else {
		p.TransactTime = val
	}
	if val, err := codec.GetFixedString(buf, 8); err != nil {
		return err
	} else {
		p.UserInfo = val
	}
	if val, err := codec.GetFixedString(buf, 10); err != nil {
		return err
	} else {
		p.ClOrdId = val
	}
	if val, err := codec.GetFixedString(buf, 12); err != nil {
		return err
	} else {
		p.AccountId = val
	}
	if val, err := codec.GetFixedString(buf, 4); err != nil {
		return err
	} else {
		p.BranchId = val
	}
	if val, err := codec.GetFixedString(buf, 4); err != nil {
		return err
	} else {
		p.OrderRestrictions = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.Side = val
	}
	if val, err := codec.GetFixedString(buf, 1); err != nil {
		return err
	} else {
		p.OrdType = val
	}
	if val, err := codec.GetBasicType[int64](buf); err != nil {
		return err
	} else {
		p.OrderQty = val
	}
	if val, err := codec.GetBasicType[int64](buf); err != nil {
		return err
	} else {
		p.Price = val
	}
	switch p.ApplId {
	case "010":
		p.ApplExtend = &Extend100101{}
	case "020":
		p.ApplExtend = &Extend100201{}
	case "030":
		p.ApplExtend = &Extend100301{}
	case "051":
		p.ApplExtend = &Extend100501{}
	case "052":
		p.ApplExtend = &Extend100501{}
	case "060":
		p.ApplExtend = &Extend100601{}
	case "061":
		p.ApplExtend = &Extend100601{}
	case "070":
		p.ApplExtend = &Extend100701{}
	case "150":
		p.ApplExtend = &Extend101501{}
	case "151":
		p.ApplExtend = &Extend101501{}
	case "152":
		p.ApplExtend = &Extend101501{}
	case "160":
		p.ApplExtend = &Extend101601{}
	case "170":
		p.ApplExtend = &Extend101701{}
	case "180":
		p.ApplExtend = &Extend101801{}
	case "181":
		p.ApplExtend = &Extend101801{}
	case "270":
		p.ApplExtend = &Extend102701{}
	case "271":
		p.ApplExtend = &Extend102701{}
	case "280":
		p.ApplExtend = &Extend102801{}
	case "281":
		p.ApplExtend = &Extend102801{}
	case "290":
		p.ApplExtend = &Extend102901{}
	case "291":
		p.ApplExtend = &Extend102901{}
	case "630":
		p.ApplExtend = &Extend106301{}
	case "350":
		p.ApplExtend = &Extend103501{}
	case "351":
		p.ApplExtend = &Extend103501{}
	case "370":
		p.ApplExtend = &Extend103701{}
	case "410":
		p.ApplExtend = &Extend104101{}
	case "417":
		p.ApplExtend = &Extend104128{}
	case "470":
		p.ApplExtend = &Extend104701{}
	default:
		return fmt.Errorf("unsupported ApplId: %v", p.ApplId)
	}
	if err := p.ApplExtend.Decode(buf); err != nil {
		return err
	}
	return nil
}
