// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestNewOrderCodec(t *testing.T) {

	applExtend := &msg.Extend100101{
		StopPx:         8,
		MinQty:         8,
		MaxPriceLevels: 2,
		TimeInForce:    "x",
		CashMargin:     "x",
	}
	original := &msg.NewOrder{
		SubmittingPbuid:   "xxxxxx",
		SecurityId:        "xxxxxxxx",
		SecurityIdsource:  "xxxx",
		OwnerType:         2,
		ClearingFirm:      "xx",
		TransactTime:      8,
		UserInfo:          "xxxxxxxx",
		ClOrdId:           "xxxxxxxxxx",
		AccountId:         "xxxxxxxxxxxx",
		BranchId:          "xxxx",
		OrderRestrictions: "xxxx",
		Side:              "x",
		OrdType:           "x",
		OrderQty:          8,
		Price:             8,
		ApplId:            "010",
		ApplExtend:        applExtend,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.NewOrder
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
