// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestPartitionReportCodec(t *testing.T) {

	original := &msg.PartitionReport{
		PartitionNo: 4,
		ReportIndex: 8,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.PartitionReport
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
