// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/szse-bin/messages"
)

func TestPlatformInfoCodec(t *testing.T) {

	platformPartition := &msg.PlatformPartition{
		PartitionNo: 4,
	}
	original := &msg.PlatformInfo{
		PlatformId:        2,
		PlatformPartition: []*msg.PlatformPartition{platformPartition},
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.PlatformInfo
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
