// Code generated by fin-protoc. DO NOT EDIT.
package szse_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// PlatformPartition represents the packet structure.
type PlatformPartition struct {
	PartitionNo int32 `json:"PartitionNo"`
}

// NewPlatformPartition creates a new instance of PlatformPartition.
func NewPlatformPartition() *PlatformPartition {
	return &PlatformPartition{}
}

// String returns a string representation of the packet.
func (p *PlatformPartition) String() string {
	return fmt.Sprintf("PlatformPartition{PartitionNo: %v}", p.PartitionNo)
}

// Encode encodes the packet into a byte slice.
func (p *PlatformPartition) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteBasicType(buf, p.PartitionNo); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "PartitionNo", err)
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *PlatformPartition) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadBasicType[int32](buf); err != nil {
		return err
	} else {
		p.PartitionNo = val
	}
	return nil
}
