// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/risk-bin/messages"
)

func TestCancelRejectCodec(t *testing.T) {

	original := &msg.CancelReject{
		ClOrdId:      "hello",
		OrigClOrdId:  "hello",
		CxlRejReason: 4,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.CancelReject
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
