// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/risk-bin/messages"
)

func TestOrderCancelCodec(t *testing.T) {

	original := &msg.OrderCancel{
		ClOrdId:     "hello",
		OrigClOrdId: "hello",
		SecurityId:  "hello",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.OrderCancel
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
