// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// OrderCancel represents the packet structure.
type OrderCancel struct {
	UniqueOrderId     string `json:"UniqueOrderID"`
	UniqueOrigOrderId string `json:"UniqueOrigOrderID"`
	ClOrdId           string `json:"ClOrdID"`
	OrigClOrdId       string `json:"OrigClOrdID"`
	SecurityId        string `json:"SecurityID"`
}

// NewOrderCancel creates a new instance of OrderCancel.
func NewOrderCancel() *OrderCancel {
	return &OrderCancel{}
}

// String returns a string representation of the packet.
func (p *OrderCancel) String() string {
	return fmt.Sprintf("OrderCancel{UniqueOrderId: %v, UniqueOrigOrderId: %v, ClOrdId: %v, OrigClOrdId: %v, SecurityId: %v}", p.UniqueOrderId, p.UniqueOrigOrderId, p.ClOrdId, p.OrigClOrdId, p.SecurityId)
}

// Encode encodes the packet into a byte slice.
func (p *OrderCancel) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteString[uint32](buf, p.UniqueOrderId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.UniqueOrigOrderId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.ClOrdId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.OrigClOrdId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.SecurityId); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *OrderCancel) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.UniqueOrderId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.UniqueOrigOrderId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.ClOrdId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.OrigClOrdId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.SecurityId = val
	}
	return nil
}
