// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/risk-bin/messages"
)

func TestOrderConfirmCodec(t *testing.T) {

	original := &msg.OrderConfirm{
		UniqueOrderId:     "hello",
		UniqueOrigOrderId: "hello",
		ClOrdId:           "hello",
		ExecType:          "x",
		OrdRejReason:      4,
		OrdCnfmId:         "hello",
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.OrderConfirm
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
