// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin

import (
	"bytes"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/codec"
)

func init() {
}

// OrderConfirm represents the packet structure.
type OrderConfirm struct {
	UniqueOrderId     string `json:"UniqueOrderID"`
	UniqueOrigOrderId string `json:"UniqueOrigOrderID"`
	ClOrdId           string `json:"ClOrdID"`
	ExecType          string `json:"ExecType"`
	OrdRejReason      uint32 `json:"OrdRejReason"`
	OrdCnfmId         string `json:"OrdCnfmID"`
}

// NewOrderConfirm creates a new instance of OrderConfirm.
func NewOrderConfirm() *OrderConfirm {
	return &OrderConfirm{}
}

// String returns a string representation of the packet.
func (p *OrderConfirm) String() string {
	return fmt.Sprintf("OrderConfirm{UniqueOrderId: %v, UniqueOrigOrderId: %v, ClOrdId: %v, ExecType: %v, OrdRejReason: %v, OrdCnfmId: %v}", p.UniqueOrderId, p.UniqueOrigOrderId, p.ClOrdId, p.ExecType, p.OrdRejReason, p.OrdCnfmId)
}

// Encode encodes the packet into a byte slice.
func (p *OrderConfirm) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.WriteString[uint32](buf, p.UniqueOrderId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.UniqueOrigOrderId); err != nil {
		return err
	}
	if err := codec.WriteString[uint32](buf, p.ClOrdId); err != nil {
		return err
	}
	if err := codec.WriteFixedString(buf, p.ExecType, 1); err != nil {
		return err
	}
	if err := codec.WriteBasicType(buf, p.OrdRejReason); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "OrdRejReason", err)
	}
	if err := codec.WriteString[uint32](buf, p.OrdCnfmId); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *OrderConfirm) Decode(buf *bytes.Buffer) error {
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.UniqueOrderId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.UniqueOrigOrderId = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.ClOrdId = val
	}
	if val, err := codec.ReadFixedString(buf, 1); err != nil {
		return err
	} else {
		p.ExecType = val
	}
	if val, err := codec.ReadBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.OrdRejReason = val
	}
	if val, err := codec.ReadString[uint32](buf); err != nil {
		return err
	} else {
		p.OrdCnfmId = val
	}
	return nil
}
