// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin_test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	msg "github.com/xinchentechnote/fin-proto-go/risk-bin/messages"
)

func TestRcBinaryCodec(t *testing.T) {

	body := &msg.NewOrder{
		UniqueOrderId: "hello",
		ClOrdId:       "hello",
		SecurityId:    "hello",
		Side:          "x",
		Price:         8,
		OrderQty:      8,
		OrdType:       "x",
		Account:       "hello",
	}
	original := &msg.RcBinary{
		Version:    4,
		MsgBodyLen: 4,
		MsgType:    100101,
		Body:       body,
	}
	var buf bytes.Buffer
	assert.NoError(t, original.Encode(&buf))
	var decoded msg.RcBinary
	assert.NoError(t, decoded.Decode(&buf))
	assert.Equal(t, original, &decoded)
}
