// Code generated by fin-protoc. DO NOT EDIT.
package risk_bin

import (
	"bytes"
	"encoding/binary"
	"fmt"

	"github.com/xinchentechnote/fin-proto-go/internal/codec"
)

// RcBinary represents the packet structure.
type RcBinary struct {
	MsgType    uint32            `json:"MsgType"`
	Version    uint32            `json:"Version"`
	MsgBodyLen uint32            `json:"MsgBodyLen"`
	Body       codec.BinaryCodec `json:"Body"`
}

// NewRcBinary creates a new instance of RcBinary.
func NewRcBinary() *RcBinary {
	return &RcBinary{}
}

// String returns a string representation of the packet.
func (p *RcBinary) String() string {
	return fmt.Sprintf("RcBinary{MsgType: %v, Version: %v, MsgBodyLen: %v, Body: %v}", p.MsgType, p.Version, p.MsgBodyLen, p.Body)
}

// Encode encodes the packet into a byte slice.
func (p *RcBinary) Encode(buf *bytes.Buffer) error {
	// Implement encoding logic here.
	if err := codec.PutBasicType(buf, p.MsgType); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MsgType", err)
	}
	if err := codec.PutBasicType(buf, p.Version); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "Version", err)
	}
	var BodyBuf bytes.Buffer
	if err := p.Body.Encode(&BodyBuf); err != nil {
		return err
	}
	p.MsgBodyLen = uint32(BodyBuf.Available())
	if err := codec.PutBasicType(buf, p.MsgBodyLen); err != nil {
		return fmt.Errorf("failed to encode %s: %w", "MsgBodyLen", err)
	}
	if err := binary.Write(buf, binary.BigEndian, BodyBuf.Bytes()); err != nil {
		return err
	}
	return nil
}

// Decode decodes the packet from a byte slice.
func (p *RcBinary) Decode(buf *bytes.Buffer) error {
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.MsgType = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.Version = val
	}
	if val, err := codec.GetBasicType[uint32](buf); err != nil {
		return err
	} else {
		p.MsgBodyLen = val
	}
	switch p.MsgType {
	case 100101:
		p.Body = &NewOrder{}
	case 200102:
		p.Body = &OrderConfirm{}
	case 200115:
		p.Body = &ExecutionReport{}
	case 190007:
		p.Body = &OrderCancel{}
	case 290008:
		p.Body = &CancelReject{}
	default:
		return fmt.Errorf("unsupported MsgType: %v", p.MsgType)
	}
	if err := p.Body.Decode(buf); err != nil {
		return err
	}
	return nil
}
